lms/urls.py
# from core.view import index

from django.conf import settings  # debug toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),

    path('students/', include('students.urls')),
    
    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),
    
    # path('', index, name='index'),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import (StudentCreateView, StudentListView, StudentUpdateView, 
                            delete_student, generate_students)

app_name = 'students'

urlpatterns = [
    path('generate', generate_students, name='generator'),
    path('', StudentListView.as_view(), name='list'),
    path('create', StudentCreateView.as_view(), name='create'),
    path('edit/<uuid:uuid>', StudentUpdateView.as_view(), name='edit'),
    path('delete/<uuid:uuid>', delete_student, name='delete'),
    
    # path('delete/<uuid:uuid>', StudentDelete.as_view(), name='delete'),
    # path('', get_students, name='list'),
    # path('create', create_student, name='create'),
    # path('edit/<uuid:uuid>', edit_student, name='edit'),

]

students/models.py
import random
import uuid

from core.models import Person

from django.db import models

from faker import Faker

from groups.models import Group


class Student(Person):
    # Все поля ниже унаследованы от класса Person
    # id = models.AutoField(primary_key=True)
    # uuid = models.UUIDField(max_length=64, null=True, default=uuid.uuid4, unique=True)
    # first_name = models.CharField(max_length=64, null=True)
    # last_name = models.CharField(max_length=64, null=True)
    # email = models.CharField(max_length=64, null=True)
    # phone = models.CharField(max_length=14, null=True)
    rating = models.SmallIntegerField(null=True, default=0)
    group = models.ForeignKey(
        to=Group,
        null=True,
        on_delete=models.SET_NULL,
        related_name='students'
    )

    def __str__(self):
        return f'{self.id}, {self.first_name}, {self.last_name}, {self.email}, {self.rating}'

    @staticmethod
    def generate_students(count):
        fake = Faker()

        group_list = list(Group.object.all())

        for i in range(count):
            persons = Student(
                first_name=fake.first_name(),
                last_name=fake.last_name(),
                email=fake.email(),
                rating=random.randint(0, 9),
                phone=fake.phone_number(),
                uuid=uuid.uuid4(),
                group=random.choice(group_list)
            )
            persons.save()
        return ('Created ', count, ' students')

students/forms.py
from django import forms
from django.core.exceptions import ValidationError

from students.models import Student


class StudentBaseForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = ['first_name', 'last_name', 'rating', 'email', 'phone', 'group']  # removed 'uuid'
  
    def clean_email(self):  # Функция для проверки валидности адреса
        email = self.cleaned_data['email']

        blacklist_domains = [
            'mail.ru'
            'yandex.ru'
        ]

        domain = email.split('@')[1]

        if domain in blacklist_domains:
            raise ValidationError('Restricted domain')

        return email
    
    def clean_phone(self):
        phone = self.cleaned_data.get('phone', None)
        try:
            int(phone)
        except (ValueError, TypeError):
            raise ValidationError('Please enter a valid phone number')
        
        return phone


class StudentCreateForm(StudentBaseForm):
    class Meta(StudentBaseForm.Meta):
        model = Student
        fields = ['first_name', 'last_name', 'rating', 'email', 'group']  
            

class StudentEditForm(StudentBaseForm):
    class Meta(StudentBaseForm.Meta):
        model = Student
        fields = ['first_name', 'last_name', 'rating', 'email', 'group']          
              
        

students/views.py
# from core.utils import format_list
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import (HttpResponse, HttpResponseBadRequest,
                         HttpResponseRedirect)
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.urls.base import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from students.forms import StudentCreateForm, StudentEditForm
from students.models import Student  # для работы с базой данных
from students.utils import gen_password, parse_length

# from students.templates import 'students-list.html'


# Create your views here.


def hello(request):  # Вставляем аргумент request
    return HttpResponse('Hello from Django')


def get_random(request):
    try:
        length = parse_length(request, 10)
    except Exception as ex:
        return HttpResponse(str(ex), status_code=400)

    result = gen_password(length)

    return HttpResponse(result)


def generate_students(request, default=5):
    count = request.GET.get('count', str(default))

    if not count.isnumeric:
        raise HttpResponseBadRequest("VALUE ERROR: int")
    if int(count) > 100:
        raise HttpResponseBadRequest("RANGE ERROR: [3..100]")
    count = int(count)
    # Student.generate_students(count)

    return HttpResponse(Student.generate_students(count))


def get_students(request):

    students = Student.objects.select_related('group').all()

    paginator = Paginator(students, 5)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    first_name = request.GET.get('first_name')
    last_name = request.GET.get('last_name')
    email = request.GET.get('email')
    phone = request.GET.get('phone')
    # rating = request.GET.get('rating')

    if first_name:
        or_names = first_name.split('|')
        or_cond = Q()   # from django.db.models import Q
        for or_name in or_names:
            or_cond = or_cond | Q(first_name=or_name)
        students = students.filter(or_cond)

    if last_name:
        students = students.filter(last_name=last_name)

    if email:
        students = students.filter(email=email)

    if phone:
        students = students.filter(email=phone)     

    return render(
        request=request,
        template_name='students-list.html',
        # context={'students': format_list(students)}

        # context={'students': students,   
        #          # 'title': 'students list'
        #          }

        context={'students': page}


    )

    # return HttpResponse(format_list(students))


# New funct with dict
""" def get_students(request):
    students = Student.objects.all()

    params = [
        'first_name',
        'last_name',
        'birthdate',
        'rating'
    ]

    for param in params:
        value = request.GET.get(param)
        if value:
            students = students.filter(**{param: value})

    # ввод через HTML форму на сайте

    # уходим в файл students-list.html

    return render(
        request=request,
        template_name='students-list.html',
        context={
            'students': format_list(students)
        }
    )

    return HttpResponse(format_list(students)) """


def create_student(request):
    if request.method == 'GET':

        form = StudentCreateForm(request.POST)

    elif request.method == 'POST':

        form = StudentCreateForm(request.POST)

        if form.is_valid():
            form.save()
            # return HttpResponseRedirect('/students')
            return HttpResponseRedirect(reverse('students:list'))

    return render(
        request=request,
        template_name='students-create.html',
        context={
            'form': form,
            # 'title': 'Create Students'
        }
    )


def edit_student(request, uuid):
    try:
        student = Student.objects.get(uuid=uuid)
    except Student.DoesNotExist as ex:
        return HttpResponse('Student does not exist', status=404)

    if request.method == 'GET':

        form = StudentEditForm(instance=student)

    elif request.method == 'POST':

        form = StudentCreateForm(
            data=request.POST,
            instance=student
        )

        if form.is_valid():
            form.save()

            # from django.urls import reverse
            # return HttpResponseRedirect('/students')
            return HttpResponseRedirect(reverse('students:list'))

    return render(
        request=request,
        template_name='students-edit.html',
        context={
            'form': form,
            'student': student,
            # 'title': 'Edit Student'
        }
    )

    # return HttpResponse('EDIT')


def delete_student(request, uuid):

    student = get_object_or_404(Student, uuid=uuid)

    student.delete()

    return HttpResponseRedirect(reverse('students:list'))


class StudentUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('accounts:login')
    model = Student
    form_class = StudentEditForm
    template_name = 'students-edit.html'
    success_url = reverse_lazy('students:list')
    context_object_name = 'student'
    pk_url_kwarg = 'uuid'

    def get_object(self):
        uuid = self.kwargs.get('uuid')
        return self.get_queryset().get(uuid=uuid)


class StudentListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('accounts:login')
    model = Student
    template_name = 'students-list.html'
    context_object_name = 'students'
    paginate_by = 5
    
    def get_queryset(self):
        # qs = self.model.objects.all()
        qs = super().get_queryset()
        qs = qs.select_related('group')
        first_name = self.request.GET.get('first_name')
        last_name = self.request.GET.get('last_name')
        email = self.request.GET.get('email')
        phone = self.request.GET.get('phone')
        rating = self.request.GET.get('rating')
        if last_name:
            qs = Student.objects.filter(last_name=last_name)
        if first_name:
            qs = Student.objects.filter(first_name=first_name)
        if email:
            qs = Student.objects.filter(email=email)
        if phone:
            qs = Student.objects.filter(phone=phone)
        if rating:
            qs = Student.objects.filter(rating=rating)

        return qs


class StudentCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('accounts:login')
    model = Student
    form_class = StudentCreateForm
    template_name = 'students-list.html'
    context_object_name = 'students'


class StudentDelete(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('accounts:login')
    model = Student
    success_url = reverse_lazy('students:list')
    pk_url_kwarg = 'uuid'

students/templates/students-create.html
{% extends 'base.html' %}

{% block title %}
    <title>Create Students</title>
{% endblock %}

{% block header %}
<header>
    <p>Create Student</p>
</header>
{% endblock %}

{% block content %}
   <!--  {% csrf_token %} -->
    <form method="POST">
        {% csrf_token %}
        
        {{form.as_p}}
  
        <input type="submit" value="Create">
    </form>
{% endblock %}

students/templates/students-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
    <title>Edit Student</title>
{% endblock %}

{% block header %}
<header>
    <p>Edit Students</p>
</header>
{% endblock %}

{% block content %}
   
    <form method="POST">
        {% csrf_token %}
      
        <!-- {{form.as_p}} -->
        {{form|crispy}}
  
        <input class="btn btn-success" type="submit" value="Save">
        <input class="btn btn-danger" formaction="{% url 'students:delete' student.uuid %}" type="submit" value="Delete">
    </form>
{% endblock %}

students/templates/students-list.html
{% extends 'base.html' %}

{% block title %}
    <title>Students List</title>
{% endblock %}

{% block header %}
<header>
    <strong><p>Students List</p></strong>
</header>
{% endblock %}

{% block content %}
<form>

  <div class="input-group mb-3">
    <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">First Name</span>
    </div>
    <input type="text" name="first_name" class="form-control" placeholder="Enter First Name" aria-label="First Name" aria-describedby="basic-addon1">
  </div>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">Last Name</span>
    </div>
    <input type="text" name="last_name" class="form-control" placeholder="Enter Last Name" aria-label="Last Name" aria-describedby="basic-addon1">
  </div>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">Rating</span>
    </div>
    <input type="text" name="rating" class="form-control" placeholder="Enter Rating" aria-label="Rating" aria-describedby="basic-addon1">
  </div>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">Email</span>
    </div>
    <input type="text" name="email" class="form-control" placeholder="Enter Email" aria-label="Email" aria-describedby="basic-addon1">
  </div>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">Phone</span>
    </div>
    <input type="text" name="phone" class="form-control" placeholder="Enter Phone" aria-label="Phone" aria-describedby="basic-addon1">
  </div>
  <!-- <div class="input-group mb-3">
    <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">UUID</span>
    </div>
    <input type="text" name="uuid" class="form-control" placeholder="Enter UUID" aria-label="UUID" aria-describedby="basic-addon1">
  </div>
  <div class="input-group mb-3">
    <div class="input-group-prepend">
    <span class="input-group-text" id="basic-addon1">Group</span>
    </div>
    <input type="text" name="group" class="form-control" placeholder="Enter Group" aria-label="Group" aria-describedby="basic-addon1">
  </div> -->



 <!--  <table style="width:25%">
    <tr>
      <th>First name</th>
      <td><input type="text" name="first_name"></td>
    </tr>
    <tr>
      <th>Last name</th>
      <td><input type="text" name="last_name"></td> 
    </tr>
    <tr>
      <th>Rating</th>
      <td><input type="number" name="rating"  min_value=0 max_value=100></td>
    </tr>
    <tr>
      <th>Email</th>
      <td><input type="text" name="email"></td>
    </tr>
    <tr>
      <th>Phone</th>
      <td><input type="text" name="phone"></td>
    </tr>
    <tr>
      <th>UUID</th>
      <td><input type="text" name="uuid"></td>
    </tr>
    <tr>
      <th>Group</th>
      <td><input type="text" name="group"></td>
    </tr>
</table> -->
<div class ="mb-1">
      <input class="btn btn-primary" type="submit" value="Search">
      <input class="btn btn-success" formaction="{% url 'students:create' %}" type="submit" value="Create">
</div>

{% include 'includes/students-table.html' %}
{% endblock %}