groups/urls.py
from django.urls import path

from groups.views import (GroupCreateView, GroupDeleteView, GroupListView, 
                          GroupUpdateView, generate_groups, 
                          )

app_name = 'groups'

urlpatterns = [
    # path('', groups_list, name='list'),
    path('', GroupListView.as_view(), name='list'),
    # path('create', create_group, name='create'),
    path('create', GroupCreateView.as_view(), name='create'),
    # path('edit/<int:id>', edit_groups, name='edit'),
    path('edit/<int:id>', GroupUpdateView.as_view(), name='edit'),
    # path('delete/<int:id>', delete_group, name='delete'),
    path('delete/<int:id>', GroupDeleteView.as_view(), name='delete'),
    path('generate', generate_groups, name='generator'),

]

lms/urls.py
# from core.view import index

from django.conf import settings  # debug toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),

    path('students/', include('students.urls')),
    
    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),
    
    # path('', index, name='index'),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

groups/models.py
import datetime
import random

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.forms import ValidationError

from faker import Faker

# from groups.views import GroupUpdateView

from teachers.models import Teacher


# Create your models here.


class Classroom(models.Model):
    name = models.CharField(max_length=32)
    floor = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(2), MaxValueValidator(5)]
    )

    def __str__(self):
        return f'{self.name}, {self.floor}'


class Group(models.Model):
    name = models.CharField(max_length=64, null=False)
    course = models.CharField(max_length=64, null=False)
    start_date = models.DateField(null=True, default=datetime.date.today)
    teacher = models.ForeignKey(
        to=Teacher,
        null=True,
        on_delete=models.SET_NULL,
        related_name='groups',
        # default=random.choice(list(Teacher.objects.all()))
    )
    supervisor = models.OneToOneField(
        to=Teacher,
        null=True,
        on_delete=models.SET_NULL,
        related_name='supervisor'
    )
    head = models.OneToOneField(
        to='students.Student',
        null=True,
        on_delete=models.SET_NULL,
        related_name='head_of_group'
    )
    classrooms = models.ManyToManyField(
        to=Classroom,
        related_name='groups'
    )

    def __str__(self):
        return f'{self.id}, {self.name}, {self.course}'

    @staticmethod
    def generate_groups(count):
        fake = Faker()
        teacher_list = list(Teacher.objects.all())
        for i in range(count):
            groups = Group(
                name=fake.bs(),
                course=fake.job(),
                teacher=random.choice(teacher_list)
            )
            groups.save()
        return ('Created ', count, ' groups')

    def clean_head(self):
        cleaned_data = super().clean()
        data = self.cleaned_data.get('head')
        data = self.head
        if data not in self.students.all():
            
            raise ValidationError('Head must be group member')

        else:
            return data

    def save(self, *args, **kwargs):

        # self.clean_head()
        super().save(*args, **kwargs)

groups/forms.py
from django import forms

from groups.models import Group


class GroupBaseForm(forms.ModelForm):
    class Meta:
        model = Group
        # fields = ['name', 'course', 'teacher', 'supervisor']
        fields = '__all__'  # включает все поля в форму
        exclude = ['start_date', 'uuid']
        

class GroupCreateForm(GroupBaseForm):
    class Meta(GroupBaseForm.Meta):
        model = Group
        fields = ['name', 'course', 'teacher', 'supervisor']
        # fields = '__all__'  # включает все поля в форму
        # exclude = ['start_date', 'uuid', 'head']


class GroupEditForm(GroupBaseForm):
    class Meta(GroupBaseForm.Meta):
        model = Group
        # fields = ['name', 'course', 'teacher', 'supervisor']
        fields = '__all__'  # включает все поля в форму
        exclude = ['start_date', 'uuid']
                     
    

groups/views.py
# from core.utils import format_list

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from groups.forms import GroupCreateForm, GroupEditForm
from groups.models import Group

# Create your views here.


def groups_list(request):
    # groups = Group.objects.all()
    groups = Group.objects.select_related('teacher').all()

    paginator = Paginator(groups, 5)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    name = request.GET.get('name')
    program = request.GET.get('program')

    if name:
        or_names = name.split('|')
        or_cond = Q()   # from django.db.models import Q
        for or_name in or_names:
            or_cond = or_cond | Q(name=or_name)
        groups = groups.filter(or_cond)

    if program:
        groups = groups.filter(program=program)

    return render(
        request=request,
        template_name='groups-list.html',
        # context={'groups': format_list(groups)}
        # context={'groups': groups}
        context={'groups': page}

    )


# def groups_list(request):
#     groups = Group.objects.all()

#     params = [
#         'name',
#         'program'

#     ]

#     for param in params:
#         value = request.GET.get(param)
#         if value:
#             groups = groups.filter(**{param: value})
#     return HttpResponse(format_list(groups))


def create_group(request):

    if request.method == "GET":

        form = GroupCreateForm()

        return render(
            request=request,
            template_name='groups-create.html',
            context={'form': form}
        )

    elif request.method == 'POST':

        form = GroupCreateForm(request.POST)

        if form.is_valid():
            form.save()
            # return HttpResponseRedirect('/groups')
            return HttpResponseRedirect(reverse('groups:list'))

    return render(
        request=request,
        template_name='groups-create.html',
        context={'form': form}
    )

    # return HttpResponseRedirect('/groups/')


def edit_groups(request, id):
    try:
        group = Group.objects.get(id=id)
    except Group.DoesNotExist as ex:
        return HttpResponse('Group does not exist', status=404)

    if request.method == 'GET':

        form = GroupEditForm(instance=group)

    elif request.method == 'POST':

        form = GroupCreateForm(
            data=request.POST,
            instance=group
        )

        if form.is_valid():
            form.save()
            # return HttpResponseRedirect('/groups')
            return HttpResponseRedirect(reverse('groups:list'))

    return render(
        request=request,
        template_name='groups-edit.html',  # Это передается в шаблон html
        context={
            'form': form,
            'group': group,
            'students': group.students.all()
        }
    )


def delete_group(request, id):

    group = get_object_or_404(Group, id=id)

    group.delete()

    return HttpResponseRedirect(reverse('groups:list'))  


def generate_groups(request, default=5):
    count = request.GET.get('count', str(default))

    if not count.isnumeric:
        raise HttpResponseBadRequest("VALUE ERROR: int")
    if int(count) > 100:
        raise HttpResponseBadRequest("RANGE ERROR: [3..100]")
    count = int(count)
    # Student.generate_students(count)

    return HttpResponse(Group.generate_groups(count))


class GroupUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('accounts:login')
    model = Group
    form_class = GroupEditForm
    template_name = 'groups-edit.html'
    success_url = reverse_lazy('groups:list')
    context_object_name = 'group'
    pk_url_kwarg = 'id'
    
    def get_object(self):
        id = self.kwargs.get('id')
        return self.get_queryset().get(id=id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['students'] = self.get_object().students.all()
        return context


class GroupListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('accounts:login')
    model = Group
    template_name = 'groups-list.html'
    context_object_name = 'groups'
    paginate_by = 5

    def get_queryset(self):
        qs = self.model.objects.all()
        # qs = super().get_queryset()
        name = self.request.GET.get('name')
        program = self.request.GET.get('program')
        if name:
            qs = Group.objects.filter(name=name)
        if program:
            qs = Group.objects.filter(program=program)
        
        return qs  


class GroupCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('accounts:login')
    model = Group
    form_class = GroupCreateForm
    template_name = 'groups-create.html'
    context_object_name = 'groups'
    success_url = reverse_lazy('groups:list')
    

class GroupDeleteView(DeleteView):
    model = Group
    pk_url_kwarg = 'id'
    success_url = reverse_lazy('groups:list')
    

groups/templates/groups-create.html
{% extends 'base.html' %}

{% block title %}
    <title>Group Create</title>
{% endblock %}

{% block header %}
<header>
    <p>Create groups</p>
</header>
{% endblock %}

{% block content %}
    <form method="POST">
        {% csrf_token %}
        <!-- <label >Group name:</label>
        <input type="text" name="name"><br><br>
  
        <label>Discipline:</label>
        <input type="text" name="program"><br><br> -->
        
        {{form.as_p}}
        <input type="submit" value="Create">
        
    </form>
{% endblock %}

groups/templates/groups-edit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block title %}
    <title>Group Edit</title>
{% endblock %}

{% block header %}
<header>
    <p>Edit groups</p>
</header>
{% endblock %}

{% block content %}
   
    <form method="POST">
        {% csrf_token %}
      
        <!-- {{form.as_p}} -->
        {{form|crispy}}
  
        <input type="submit" value="Save">
        <input formaction="{% url 'groups:delete' group.id %}" type="submit" value="Delete">
    </form>
{% include 'includes/students-table.html' %}    

{% endblock %}

groups/templates/groups-list.html
{% extends 'base.html' %}

{% block title %}
    <title>Groups List</title>
{% endblock %}

{% block header %}
<header>
    <strong><p>List of groups</p></strong>
</header>
{% endblock %}

{% block content %}

    <form>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Group Name</span>
            </div>
            <input type="text" name="name" class="form-control" placeholder="Enter Group Name" aria-label="Group Name" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Course</span>
            </div>
            <input type="text" name="program" class="form-control" placeholder="Enter group course" aria-label="Group Programm" aria-describedby="basic-addon1">
          </div>

      <!-- <label >Group name:</label>
      <input type="text" name="name"><br><br>

      <label>Group Programm:</label>
      <input type="text" name="program"><br><br> -->

      <input class="btn btn-primary" type="submit" value="Search">
      <input class="btn btn-success" formaction="{% url 'groups:create' %}" type="submit" value="Add new">

    </form>

<!-- {{groups|safe}} -->

<!-- <table>
    <tr>
        <th>EDIT</th>
        <th>Group ID</th>
        <th>Group Name</th>
        <th>Course</th>
        <th>Teacher</th>
        <th>Supervisor</th>
        
    </tr>

    {% for group in groups %}
  
    <tr>
      <td><a href="{% url 'groups:edit' group.id%}">EDIT</a></td>
      <td>{{ group.id }}</td>>
      <td>{{ group.name }}</td>
      <td>{{ group.course }}</td>
      <td>{{ group.teacher.first_name}} {{ group.teacher.last_name}}</td>
      <td>{{ group.supervisor.first_name }} {{ group.supervisor.last_name }}</td>
    </tr>
    {% endfor %} -->

{% include 'includes/groups-tables.html' %}

{% endblock %}