lms/urls.py
# from core.view import index

from django.conf import settings  # debug toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),

    path('students/', include('students.urls')),
    
    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),
    
    # path('', index, name='index'),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

teachers/urls.py
from django.urls import path

from teachers.views import (TeacherCreateView, TeacherListView, TeacherUpdateView, 
                            delete_teacher, generate_teachers,
                            )


app_name = 'teachers'

urlpatterns = [
    path('generate', generate_teachers, name='generator'),
    # path('create', create_teacher, name='create'),
    path('create', TeacherCreateView.as_view(), name='create'),
    # path('', teachers_list, name='list'),
    path('', TeacherListView.as_view(), name='list'),
    # path('edit/<int:id>', edit_teachers, name='edit'),
    path('edit/<int:id>', TeacherUpdateView.as_view(), name='edit'),
    path('delete/<int:id>', delete_teacher, name='delete'),
    
]

teachers/models.py
import uuid

from core.models import Person

from django.db import models

from faker import Faker


class Teacher(Person):
    # first_name = models.CharField(max_length=64, null=False)
    # last_name = models.CharField(max_length=64, null=False)
    prof = models.CharField(max_length=64, null=False)
    
    def __str__(self):

        return f'{self.id}, {self.first_name}, {self.last_name}, {self.prof}'

    @staticmethod
    def generate_teachers(count):
        fake = Faker()

        for i in range(count):
            persons = Teacher(
                first_name=fake.first_name(),
                last_name=fake.last_name(),
                email=fake.email(),
                phone=fake.phone_number(),
                uuid=uuid.uuid4(),
                prof=fake.job())
            persons.save()
        return ('Created ', count, ' teachers')
        
    # def save(self, *args, **kwargs):
    #     self.write_date = datetime.date.today()
    #     super().save(*args, **kwargs)
        

teachers/forms.py
from django import forms

from teachers.models import Teacher


class TeacherBaseForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = ['first_name', 'last_name', 'prof']


class TeacherCreateForm(TeacherBaseForm):
    class Meta(TeacherBaseForm.Meta):
        model = Teacher
        fields = ['first_name', 'last_name', 'prof']


class TeacherEditForm(TeacherBaseForm):
    class Meta(TeacherBaseForm.Meta):
        model = Teacher
        fields = ['first_name', 'last_name', 'prof']
        

teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.http import HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView

from teachers.forms import TeacherCreateForm, TeacherEditForm
from teachers.models import Teacher


# Create your views here.


def teachers_list(request):
    teachers = Teacher.objects.all()

    paginator = Paginator(teachers, 5)
    page_number = request.GET.get('page', 1)
    page = paginator.get_page(page_number)

    first_name = request.GET.get('first_name')
    last_name = request.GET.get('last_name')
    prof = request.GET.get('prof')

    if first_name:
        or_names = first_name.split('|')
        or_cond = Q()   # from django.db.models import Q
        for or_name in or_names:
            or_cond = or_cond | Q(first_name=or_name)
        teachers = teachers.filter(or_cond)

    if last_name:
        teachers = teachers.filter(last_name=last_name)

    if prof:
        teachers = teachers.filter(prof=prof)

    return render(
        request=request,
        template_name='teachers-list.html',
        # context={'teachers': format_list(teachers)}
        # context={'teachers': teachers}
        context={'teachers': page}

    )


# def teachers_list(request):
#     teachers = Teacher.objects.all()

#     params = [
#         'first_name',
#         'last_name',
#         'prof'

#     ]

#     for param in params:
#         value = request.GET.get(param)
#         if value:
#             teachers = teachers.filter(**{param: value})
#     return HttpResponse(format_list(teachers))


def generate_teachers(request, default=5):
    count = request.GET.get('count', str(default))

    if not count.isnumeric:
        raise HttpResponseBadRequest("VALUE ERROR: int")
    if int(count) > 100:
        raise HttpResponseBadRequest("RANGE ERROR: [3..100]")

    count = int(count)

    return HttpResponse(Teacher.generate_teachers(count))

# Вариант функции с использованием GET запросов и тегов форм в html шаблоне


def teacher_create_get(request):
    if not request.GET:
        return render(
            request=request,
            template_name='teachers-create.html',


        )
        HttpResponseRedirect('/teachers/')
    else:
        first_name = request.GET.get('first_name')
        last_name = request.GET.get('last_name')
        prof = request.GET.get('prof')

        tea = Teacher.objects.create(
            first_name=first_name,
            last_name=last_name,
            prof=prof
        )
        tea.save()

        # return HttpResponseRedirect('/teachers/')
        return HttpResponseRedirect(reverse(teachers_list))


# Вариант функции с использованием класса Django forms, и файла forms.py


def create_teacher(request):

    if request.method == 'GET':
        form = TeacherCreateForm()
        return render(
            request=request,
            template_name='teachers-create.html',
            context={'form': form},
        )
        HttpResponseRedirect('/teachers/')
    elif request.method == 'POST':
        form = TeacherCreateForm(request.POST)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('teachers:list'))

        # Блок ниже делает все тоже самое, что блок наверху .

        """ first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        teacher_prof = request.POST.get('teacher_prof')

        tea = Teacher.objects.create(
            first_name=first_name,
            last_name=last_name,
            prof=prof
        )
        tea.save()

        return HttpResponseRedirect('/teachers/')
     """


def edit_teachers(request, id):
    try:
        teacher = Teacher.objects.get(id=id)
    except Teacher.DoesNotExist as ex:
        return HttpResponse('Teacher does not exist', status=404)

    if request.method == 'GET':

        form = TeacherEditForm(instance=teacher)

    elif request.method == 'POST':

        form = TeacherCreateForm(
            data=request.POST,
            instance=teacher
        )

        if form.is_valid():
            form.save()
            # return HttpResponseRedirect('/teachers')
            return HttpResponseRedirect(reverse('teachers:list'))

    return render(
        request=request,
        template_name='teachers-edit.html',
        context={
            'form': form,
            'teacher': teacher,
            'groups': teacher.groups.all()
        }
    )

    return HttpResponse('EDIT')


def delete_teacher(request, id):

    teacher = get_object_or_404(Teacher, id=id)

    teacher.delete()

    return HttpResponseRedirect(reverse('teachers:list'))    


class TeacherUpdateView(LoginRequiredMixin, UpdateView):
    login_url = reverse_lazy('accounts:login')
    model = Teacher
    form_class = TeacherEditForm
    template_name = 'teachers-edit.html'
    success_url = reverse_lazy('teachers:list')
    context_object_name = 'teacher'
    pk_url_kwarg = 'id'

    def get_object(self):
        id = self.kwargs.get('id')
        return self.get_queryset().get(id=id)


class TeacherListView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('accounts:login')
    model = Teacher
    template_name = 'teachers-list.html'
    context_object_name = 'teachers'
    paginate_by = 5

    def get_queryset(self):
        qs = self.model.objects.all()
        
        first_name = self.request.GET.get('first_name')
        last_name = self.request.GET.get('last_name')
        prof = self.request.GET.get('prof')
        if last_name:
            qs = Teacher.objects.filter(last_name=last_name)
        if first_name:
            qs = Teacher.objects.filter(first_name=first_name)
        if prof:
            qs = Teacher.objects.filter(prof=prof)
        
        return qs


class TeacherCreateView(LoginRequiredMixin, CreateView):
    login_url = reverse_lazy('accounts:login')
    model = Teacher
    form_class = TeacherCreateForm
    template_name = 'teachers-list.html'
    context_object_name = 'teachers'

teachers/templates/teachers-create.html
{% extends 'base.html' %}

{% block title %}
    <title>Teachers Create</title>
{% endblock %}

{% block header %}
<header>
    <p>Create Teachers</p>
</header>
{% endblock %}

{% block content %}
   
    <form method="POST">
        {% csrf_token %}
        <!-- <label >First name:</label>
        <input type="text" name="first_name"><br><br>
  
        <label>Last name:</label>
        <input type="text" name="last_name"><br><br>
  
        <label>Profession:</label>
        <input type="text" name="prof"><br><br> -->
  
        {{form.as_p}}
        <input type="submit" value="Create">
    </form>
{% endblock %}

teachers/templates/teachers-edit.html
{% extends 'base.html' %}

{% block title %}
    <title>Teacher edit</title>
{% endblock %}

{% block header %}
<header>
    <p>Edit Teachers</p>
</header>
{% endblock %}

{% block content %}
{% load crispy_forms_tags %}
   
    <form method="POST">
        {% csrf_token %}
      
        <!-- {{form.as_p}} -->
        {{form|crispy}}
  
        <input type="submit" value="Save">
        <input formaction="{% url 'teachers:delete' teacher.id %}" type="submit" value="Delete">
    </form>
{% include 'includes/groups-tables.html' %}
{% endblock %}

teachers/templates/teachers-list.html
{% extends 'base.html' %}

{% block title %}
    <title>Teachers List</title>
{% endblock %}

{% block header %}
<header>
    <strong><p>List of Teachers</p></strong>
</header>
{% endblock %}

{% block content %}

    <form>
        <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">First Name</span>
            </div>
            <input type="text" name="first_name" class="form-control" placeholder="Enter First Name" aria-label="First Name" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Last Name</span>
            </div>
            <input type="text" name="last_name" class="form-control" placeholder="Enter Last Name" aria-label="Last Name" aria-describedby="basic-addon1">
          </div>
          <div class="input-group mb-3">
            <div class="input-group-prepend">
            <span class="input-group-text" id="basic-addon1">Proff.</span>
            </div>
            <input type="text" name="prof" class="form-control" placeholder="Enter Profession" aria-label="Proff." aria-describedby="basic-addon1">
          </div>

      <!-- <label >First name:</label>
      <input type="text" name="first_name"><br><br>

      <label>Last name:</label>
      <input type="text" name="last_name"><br><br>

      <label>Profession:</label>
      <input type="text" name="Prof"><br><br>
 -->
      <input class="btn btn-primary" type="submit" value="Search">
      <input class="btn btn-success" formaction="{% url 'teachers:create' %}" type="submit" value="Add new">

    </form>

<!--{{teachers|safe}} -->

<table>
    <tr>
        <th>EDIT</th>
        <th>ID</th>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Profession</th>
        <th>Groups</th>
       
    </tr>

    {% for teacher in teachers %}
  
    <tr>
      <td><a href="{% url 'teachers:edit' teacher.id%}">EDIT</a></td>
      <td> {{ teacher.id }}</td>>
      <td>{{ teacher.first_name }}</td>
      <td>{{ teacher.last_name }}</td>
      <td>{{ teacher.prof }}</td>
      <td>{{ teacher.group.name }}</td>
    </tr>
    {% endfor %}


  {% include 'includes/pagination.html' %}

<!-- Paginator tab below -->
<!-- <nav aria-label="...">
  <ul class="pagination">
    <li class="page-item disabled">
  {% if page_obj.has_previous %}
  <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Previous</a>
    </li>
  {% else %}
  <li class="page-item">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
    </li>
  {% endif %}
    </li>   
       

    {% for n in page_obj.paginator.page_range %}
       {% if page_obj.number == n %}
       <li class="page-item active" aria-current="page">
          <a class="page-link" href="?page={{ n }}">{{ n }}</a>
        </li>
       {% else %}
      <li class="page-item">
          <a class="page-link" href="?page={{ n }}">{{ n }}</a>
      </li>
       {% endif %}

    {% endfor %}

    {% if page_obj.has_next %}
  <li class="page-item">
      <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
    </li>
  {% else %}
  <li class="page-item">
      <a class="page-link" href="#" tabindex="-1" aria-disabled="true">Next</a>
    </li>
  {% endif %}
  </ul>
</nav>



{% endblock %}

  -->