accounts/urls.py
from accounts.views import (AccountCreateView, AccountLoginView, AccountLogoutView, 
                            AccountPasswordView, AccountUpdateView)

from django.urls import path


app_name = 'accounts'

urlpatterns = [
    path('register', AccountCreateView.as_view(), name='register'),
    path('login', AccountLoginView.as_view(), name='login'),
    path('logout', AccountLogoutView.as_view(), name='logout'),
    path('profile', AccountUpdateView.as_view(), name='profile'),
    path('password', AccountPasswordView.as_view(), name='password'),
]

core/urls.py
from core.view import index

from django.urls import path


app_name = 'core'

urlpatterns = [
    path('', index, name='index'),  

]

groups/urls.py
from django.urls import path

from groups.views import (GroupCreateView, GroupDeleteView, GroupListView, 
                          GroupUpdateView, generate_groups, 
                          )

app_name = 'groups'

urlpatterns = [
    # path('', groups_list, name='list'),
    path('', GroupListView.as_view(), name='list'),
    # path('create', create_group, name='create'),
    path('create', GroupCreateView.as_view(), name='create'),
    # path('edit/<int:id>', edit_groups, name='edit'),
    path('edit/<int:id>', GroupUpdateView.as_view(), name='edit'),
    # path('delete/<int:id>', delete_group, name='delete'),
    path('delete/<int:id>', GroupDeleteView.as_view(), name='delete'),
    path('generate', generate_groups, name='generator'),

]

lms/urls.py
# from core.view import index

from django.conf import settings  # debug toolbar
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from students.views import get_random, hello

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', hello),
    path('password/', get_random),

    path('students/', include('students.urls')),
    
    path('teachers/', include('teachers.urls')),

    path('groups/', include('groups.urls')),
    
    # path('', index, name='index'),
    path('', include('core.urls')),
    path('accounts/', include('accounts.urls')),
]

urlpatterns += \
    static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

students/urls.py
from django.urls import path

from students.views import (StudentCreateView, StudentListView, StudentUpdateView, 
                            delete_student, generate_students)

app_name = 'students'

urlpatterns = [
    path('generate', generate_students, name='generator'),
    path('', StudentListView.as_view(), name='list'),
    path('create', StudentCreateView.as_view(), name='create'),
    path('edit/<uuid:uuid>', StudentUpdateView.as_view(), name='edit'),
    path('delete/<uuid:uuid>', delete_student, name='delete'),
    
    # path('delete/<uuid:uuid>', StudentDelete.as_view(), name='delete'),
    # path('', get_students, name='list'),
    # path('create', create_student, name='create'),
    # path('edit/<uuid:uuid>', edit_student, name='edit'),

]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
  <title>LMS</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  
  <style>
    table {
      font-family: arial, sans-serif;
      border-collapse: collapse;
      width: 100%;
    }
    
    td, th {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }
    
    tr:nth-child(even) {
      background-color: #dddddd;
    }
</style>
</head>

<body>
    {% block title %}
    <title>LMS</title>
    {% endblock %}
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'core:index' %}">LMS</a></h5>
        <nav class="my-2 my-md-0 mr-md-3">

         
          <a class="p-2 text-dark" href="{% url 'students:list' %}">Students</a>
          <a class="p-2 text-dark" href="{% url 'teachers:list' %}">Teachers</a>
          <a class="p-2 text-dark" href="{% url 'groups:list' %}">Groups</a>
          
          <!-- <div class="btn-toolbar">
            <button type="button" id="btnSubmit" class="btn btn-primary btn-sm" href="#">Sign up</a>
            <button type="button" id="btnCancel" class="btn btn-primary btn-sm"href="{% url 'accounts:register' %}">Register</a>
          </div>  -->

        </nav>
   
         <!-- {{ user  }} -->
         {% if user.is_authenticated %}
          <div class="img-circle.vert">
          <img class="rounded-circle p-1 m-1" width="40" height="40"  src="{{ user.profile.image.url }}">
          </div>

            <a class="mb-2 mr-2 btn btn-outline-primary btn-sm" href="{% url 'accounts:profile' %}">Profile({{ user }})</a>
            <a class="mb-2 mr-2 btn btn-outline-primary btn-sm" href="{% url 'accounts:logout' %}">Logout</a>
         {% else %}
            <a class="mb-2 mr-2 btn btn-outline-primary btn-sm" href="{% url 'accounts:login' %}">Sign In</a>
            <a class="mb-2 mr-2 btn btn-outline-primary btn-sm" href="{% url 'accounts:register' %}">Register</a>
         {% endif %}

        
      </div>
    
    <div class="border border-primary rounded-pill text-center m-3">
      
    {% block header %}
    
    <header>
      {% include 'includes/messages.html' %}
      <strong><p>Welcome to LMS</p></strong>
  </header>
    {% endblock %}
    </div>   

    

    {% block content %}

    {% endblock %}
     

</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    <title>Main Pages</title>
{% endblock %}

{% block content %}

<div class="container">
  <div class="card-deck mb-3 text-center">

    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Students</h4>
      </div>
      <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4"> 
        </ul>
        <h1><a class="p-2 text-dark" href="{% url 'students:list' %}">Students</a></h1>
        </div>
    </div>

    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Teachers</h4>
      </div>
      <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4"> 
        </ul>
        <h1><a class="p-2 text-dark" href="{% url 'teachers:list' %}">Teachers</a></h1>
        </div>
    </div>


    <div class="card mb-4 shadow-sm">
      <div class="card-header">
        <h4 class="my-0 font-weight-normal">Groups</h4>
      </div>
      <div class="card-body">
        <ul class="list-unstyled mt-3 mb-4"> 
        </ul>
        <h1><a class="p-2 text-dark" href="{% url 'groups:list' %}">Groups</a></h1>
        </div>
    </div>

    </div>
  </div>
  <!-- <a href="{% url 'students:list' %}">Students List</a><br>
  <a href="{% url 'groups:list' %}">Groups List</a><br>
  <a href="{% url 'teachers:list' %}">Teachers List</a><br> -->

{% endblock %}